### ISSUE TITLE
(suggestion) Profile customization

### ISSUE THREAD

**Issue by iagrib** [odota/core#1250]
Would be nice if people could customize their profiles. For example make some data private, change colour scheme, feature their best matches to be displayed over others and other stuff like this.

**Comment by howardchung** [comment]
I'd rather not add privacy controls, since it makes the API more difficult to use if players will randomly have data missing.  If a user does not want to share their data, having "Expose Public Match Data" disabled in the client will anonymize them (the data is collected but not linked to their account).

As for color and layout, I'd like to make it possible for power users to configure this, but probably this is best done on the client side rather than the server side.  I'd prefer not to have to save state for each user if it can be avoided.  (examples would be extensions like Reddit Enhancement Suite and Better Twitch TV)

**Comment by howardchung** [comment]
swapping to UI
