### ISSUE TITLE
Questions about retriever.js and Steam account

### ISSUE THREAD

**Issue by luokerenz** [odota/core#1427]
Hi, 
I have been testing the retriever.js for some days and got some questions about this script. I have successfully ran this script on a nodejs docker and used it to get replay salt. However the main issue is that the requestMatchDetails function only works for about 30 matches and after that, there would be no response. I can switch to another new account and get another 30ish replay salts before the new account fails. Other methods such as getPlayerProfile works normally. I also tested using the actual Dota game and for old account I cannot get match info by searching match id, so I assume the limit for this kind of request is pretty low.
So my question would be: how many accounts are you guys using in your server, what is the request limit before the account become useless and does the steam account need some special treatment (play some matches etc.)? Thanks.

**Comment by howardchung** [comment]
My understanding is that the limit is 100 salts/account/day.

Daily match volume usually ranges from 1 to 1.5 million matches, so you'd need 10,000 to 15,000 accounts in order to get every salt.

If you are planning on doing this at scale, you can use the OpenDota API to retrieve salts rather than creating an army of bots (which might cause a lot of load on Valve servers).
