### ISSUE TITLE
Incorrect results in explorer query when filter by team

### ISSUE THREAD

**Issue by ThePianoDentist** [odota/core#1447]
This query https://stage.opendota.com/explorer?team=726228&patch=7.05
Team: Vici Gaming, Patch: 7.05

has results including this match:
https://stage.opendota.com/matches/3117724659
Neither team are Vici Gaming

The player DDC (http://wiki.teamliquid.net/dota2/DDC)
played on Vici Gaming in 7.05, before moving to LGD Forever Young on 2017-04-08

2nd example:

https://stage.opendota.com/explorer?team=2006913&patch=7.05
Team: Vega Squadron

results contains many wrong matches, including 
https://stage.opendota.com/matches/3132006579

Here this is due to Sonneiko being considered as 'on Vega' despite being transferred off team 2017-03-31

from the new players G does show up in results, but Alohadance, Afterlife and Silent do not

**Comment by ThePianoDentist** [comment]
doing select teams gives me
`(3722485,"B)ears","B)")`
oddly. teams.team_id is "B)ears", not 3722485. Unsure if this is intended.

Do not know how to get the team id field for filtering through that
(current filtering done through notable_players.team_id)

**Comment by howardchung** [comment]
Hi, this is due to https://github.com/odota/ui/issues/865

Essentially there are two concepts of team, "current team" and "team at time of match".  The current team filter only supports the first definition, so I probably need to add a second team field that filters on the persistent team (which does not change no matter how the players move).

To do this you would join with the team_match table and then filter on the team_id there (instead of notable_players.team_id)

Question: Is there a reason you're using the stage UI rather than production?

**Comment by ThePianoDentist** [comment]
when I google "open dota explorer", stage is the first result that comes up

I understand now. 
A checkbox, that had a name explaining how team filtering can have two different meanings, which toggled between the two modes, would be ideal for me. But it's certainly an awkward problem

thanks for sql response as well. Will use that

**Comment by howardchung** [comment]
Closing as duplicate, please see the linked issue in odota/ui.
