### ISSUE TITLE
Bug in Match Filtering by Patch

### ISSUE THREAD

**Issue by mdiller** [odota/core#2273]
**Current Behavior**
Selecting a patch results in matches that might be from other patches

In this example, monkey king was introduced in patch 7.00, but it says I played him in the patch beforehand.
![image](https://user-images.githubusercontent.com/3231343/98594076-f8cccc80-2288-11eb-8b3b-4e3f404b87fb.png)
My steam id is 95211699, and the match id in question is 2849408684. One thing worthy of note is that if you check the data for that match, opendota actually correctly flags it as patch "19", which is the correct one, 7.00.

Also interesting is that https://api.opendota.com/api/players/95211699/matches?patch=18 also has the incorrect match, which is why I'm suspecting that its a core issue, and I'm posting the issue here.

**Expected behavior/code**
The filter should only allow matches from that patch.,

**Comment by howardchung** [comment]
This is most likely
* Edge matches: We don't update the patch data immediately after a patch so any monkey king patches played after 7.00 and before we got to the update would show under the old patch.

I believe the match data might be correct since we compute that on the fly. However, we also store a copy into Cassandra which is used for listing matches but is not computed.

**Comment by mdiller** [comment]
Ah, ok interesting. Good to know!
