### ISSUE TITLE
Map of all deaths for a single hero on Death Map

### ISSUE THREAD

**Issue by albertcui** [odota/core#828]
From Twitter - "was looking at teamfight death map - would be cool to see all deaths of 1 hero mapped, too. also, overlaid with heat map?"

**Comment by howardchung** [comment]
Are you interested in doing this?  I am not

**Comment by howardchung** [comment]
Reasons:

* The current implementation of death map is hacky.  We're reverse-lookuping the hero who died's approximate position at death time (based on the position data we collect every second).  I don't really want to build on top of this shaky foundation.
* The map is annoying to render because the position CSS puts the top left corner of the icon on the map.  better would be centering it at that location.

**Comment by howardchung** [comment]
Assigning to @albertcui , if you think it's still worth doing, you can take ownership of it.  If not, close :)

**Comment by howardchung** [comment]
Haven't heard anything on this lately.  The current death map is based only on teamfight deaths, not all deaths.  If we want to do a comprehensive death map, we need to track the death positions of all heroes, not just those who die in teamfights.

**Comment by heqiuzhi** [comment]
@albertcui  <Map of all deaths for a single hero on Death Map > Can you do this?
